### ISSUE TITLE
cancel answer/stopsurvey

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie-examples#1]
I believe it would be nice to allow users to stop completing the survey and cancel their responses. This functionality may be useful if they realize that they have pressed the wrong button or if they do not have time to got through all questions. This could be implemented as follows: if the user presses the button on the side of the watch all the previous answers (current survey only) are deleted.

**Comment by pjayathissa** [comment]
I imagine an implementation to look as follows

- If a user accidentally enters the flow of questions they can use the left physical button to exit
- However if the screen automatically enters the flow through a buzzed prompt, then the user has to answer the question.

Instead of the side button, we might even make a small `x` on the top right corner of the screen

@talantbekov123 do you have time to start working on this feature?

**Comment by talantbekov123** [comment]
If it is not urgent I will do it, is it okay if I make changes this Friday or during the weekend (26 - 27th October)? @pjayathissa

**Comment by pjayathissa** [comment]
Hi @talantbekov123 

Not it's not urgent at all. The weekend of the 26-27 October is perfect

**Comment by FedericoTartarini** [comment]
On the fitbit website it is stated that "clock faces cannot use the hardware buttons, but apps can", hence, would it be possible to implement the following solution: "If a user accidentally enters the flow of questions they can use the left physical button to exit"?

**Comment by pjayathissa** [comment]
@FedericoTartarini That's good to know

In which case we put a small `x` in the top left corner that the user can press to exit.

FYI @talantbekov123

**Comment by FedericoTartarini** [comment]
I am taking care of this issue and I have already written the majority of the code
